Global $__AL_KEYWORDS[44] = [ _
        "And", _
        "ByRef", _
        "Case", _
        "Const", _
        "ContinueCase", _
        "ContinueLoop", _
        "Default", _
        "Dim", _
        "Do", _
        "Else", _
        "ElseIf", _
        "EndFunc", _
        "EndIf", _
        "EndSelect", _
        "EndSwitch", _
        "EndWith", _
        "Enum", _
        "Exit", _
        "ExitLoop", _
        "False", _
        "For", _
        "Func", _
        "Global", _
        "If", _
        "In", _
        "Local", _
        "Next", _
        "Not", _
        "Null", _
        "Or", _
        "ReDim", _
        "Return", _
        "Select", _
        "Static", _
        "Step", _
        "Switch", _
        "Then", _
        "To", _
        "True", _
        "Until", _
        "Volatile", _
        "WEnd", _
        "While", _
        "With"]
