Global $__AL_FUNCS[498] = [ _
		"Abs", _
		"ACos", _
		"AdlibRegister", _
		"AdlibUnRegister", _
		"Asc", _
		"AscW", _
		"ASin", _
		"Assign", _
		"ATan", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItSetOption", _
		"AutoItWinGetTitle", _
		"AutoItWinSetTitle", _
		"Beep", _
		"Binary", _
		"BinaryLen", _
		"BinaryMid", _
		"BinaryToString", _
		"BitAND", _
		"BitNOT", _
		"BitOR", _
		"BitRotate", _
		"BitShift", _
		"BitXOR", _
		"BlockInput", _
		"Break", _
		"Call", _
		"CDTray", _
		"Ceiling", _
		"Chr", _
		"ChrW", _
		"ClipGet", _
		"ClipPut", _
		"ConsoleRead", _
		"ConsoleWrite", _
		"ConsoleWriteError", _
		"ControlClick", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlCommand", _
		"ControlDisable", _
		"ControlEnable", _
		"ControlFocus", _
		"ControlGetFocus", _
		"ControlGetHandle", _
		"ControlGetPos", _
		"ControlGetText", _
		"ControlHide", _
		"ControlListView", _
		"ControlListView", _
		"ControlListView", _
		"ControlListView", _
		"ControlListView", _
		"ControlListView", _
		"ControlListView", _
		"ControlListView", _
		"ControlListView", _
		"ControlListView", _
		"ControlListView", _
		"ControlListView", _
		"ControlListView", _
		"ControlMove", _
		"ControlSend", _
		"ControlSetText", _
		"ControlShow", _
		"ControlTreeView", _
		"Cos", _
		"Dec", _
		"DirCopy", _
		"DirCreate", _
		"DirGetSize", _
		"DirMove", _
		"DirRemove", _
		"DllCall", _
		"DllCallAddress", _
		"DllCallbackFree", _
		"DllCallbackGetPtr", _
		"DllCallbackRegister", _
		"DllClose", _
		"DllOpen", _
		"DllStructCreate", _
		"DllStructGetData", _
		"DllStructGetPtr", _
		"DllStructGetSize", _
		"DllStructSetData", _
		"DriveGetDrive", _
		"DriveGetFileSystem", _
		"DriveGetLabel", _
		"DriveGetSerial", _
		"DriveGetType", _
		"DriveMapAdd", _
		"DriveMapDel", _
		"DriveMapGet", _
		"DriveSetLabel", _
		"DriveSpaceFree", _
		"DriveSpaceTotal", _
		"DriveStatus", _
		"EnvGet", _
		"EnvSet", _
		"EnvUpdate", _
		"Eval", _
		"Execute", _
		"Exp", _
		"FileChangeDir", _
		"FileClose", _
		"FileCopy", _
		"FileCreateNTFSLink", _
		"FileCreateShortcut", _
		"FileDelete", _
		"FileExists", _
		"FileFindFirstFile", _
		"FileFindNextFile", _
		"FileFlush", _
		"FileGetAttrib", _
		"FileGetEncoding", _
		"FileGetLongName", _
		"FileGetPos", _
		"FileGetShortcut", _
		"FileGetShortName", _
		"FileGetSize", _
		"FileGetTime", _
		"FileGetVersion", _
		"FileInstall", _
		"FileMove", _
		"FileOpen", _
		"FileOpenDialog", _
		"FileRead", _
		"FileReadLine", _
		"FileReadToArray", _
		"FileRecycle", _
		"FileRecycleEmpty", _
		"FileSaveDialog", _
		"FileSelectFolder", _
		"FileSetAttrib", _
		"FileSetEnd", _
		"FileSetPos", _
		"FileSetTime", _
		"FileWrite", _
		"FileWriteLine", _
		"Floor", _
		"FtpSetProxy", _
		"FuncName", _
		"GUICreate", _
		"GUICtrlCreateAvi", _
		"GUICtrlCreateButton", _
		"GUICtrlCreateCheckbox", _
		"GUICtrlCreateCombo", _
		"GUICtrlCreateContextMenu", _
		"GUICtrlCreateDate", _
		"GUICtrlCreateDummy", _
		"GUICtrlCreateEdit", _
		"GUICtrlCreateGraphic", _
		"GUICtrlCreateGroup", _
		"GUICtrlCreateIcon", _
		"GUICtrlCreateInput", _
		"GUICtrlCreateLabel", _
		"GUICtrlCreateList", _
		"GUICtrlCreateListView", _
		"GUICtrlCreateListViewItem", _
		"GUICtrlCreateMenu", _
		"GUICtrlCreateMenuItem", _
		"GUICtrlCreateMonthCal", _
		"GUICtrlCreateObj", _
		"GUICtrlCreatePic", _
		"GUICtrlCreateProgress", _
		"GUICtrlCreateRadio", _
		"GUICtrlCreateSlider", _
		"GUICtrlCreateTab", _
		"GUICtrlCreateTabItem", _
		"GUICtrlCreateTreeView", _
		"GUICtrlCreateTreeViewItem", _
		"GUICtrlCreateUpdown", _
		"GUICtrlDelete", _
		"GUICtrlGetHandle", _
		"GUICtrlGetState", _
		"GUICtrlRead", _
		"GUICtrlRecvMsg", _
		"GUICtrlRegisterListViewSort", _
		"GUICtrlSendMsg", _
		"GUICtrlSendToDummy", _
		"GUICtrlSetBkColor", _
		"GUICtrlSetColor", _
		"GUICtrlSetCursor", _
		"GUICtrlSetData", _
		"GUICtrlSetDefBkColor", _
		"GUICtrlSetDefColor", _
		"GUICtrlSetFont", _
		"GUICtrlSetGraphic", _
		"GUICtrlSetImage", _
		"GUICtrlSetLimit", _
		"GUICtrlSetOnEvent", _
		"GUICtrlSetPos", _
		"GUICtrlSetResizing", _
		"GUICtrlSetState", _
		"GUICtrlSetStyle", _
		"GUICtrlSetTip", _
		"GUIDelete", _
		"GUIGetCursorInfo", _
		"GUIGetMsg", _
		"GUIGetStyle", _
		"GUIRegisterMsg", _
		"GUISetAccelerators", _
		"GUISetBkColor", _
		"GUISetCoord", _
		"GUISetCursor", _
		"GUISetFont", _
		"GUISetHelp", _
		"GUISetIcon", _
		"GUISetOnEvent", _
		"GUISetState", _
		"GUISetStyle", _
		"GUIStartGroup", _
		"GUISwitch", _
		"Hex", _
		"HotKeySet", _
		"HttpSetProxy", _
		"HttpSetUserAgent", _
		"HWnd", _
		"InetClose", _
		"InetGet", _
		"InetGetInfo", _
		"InetGetSize", _
		"InetRead", _
		"IniDelete", _
		"IniRead", _
		"IniReadSection", _
		"IniReadSectionNames", _
		"IniRenameSection", _
		"IniWrite", _
		"IniWriteSection", _
		"InputBox", _
		"Int", _
		"IsAdmin", _
		"IsArray", _
		"IsBinary", _
		"IsBool", _
		"IsDeclared", _
		"IsDllStruct", _
		"IsFloat", _
		"IsFunc", _
		"IsHWnd", _
		"IsInt", _
		"IsKeyword", _
		"IsMap", _
		"IsNumber", _
		"IsObj", _
		"IsPtr", _
		"IsString", _
		"Log", _
		"MapAppend", _
		"MapExists", _
		"MapKeys", _
		"MapRemove", _
		"MemGetStats", _
		"Mod", _
		"MouseClick", _
		"MouseClickDrag", _
		"MouseDown", _
		"MouseGetCursor", _
		"MouseGetPos", _
		"MouseMove", _
		"MouseUp", _
		"MouseWheel", _
		"MsgBox", _
		"Number", _
		"ObjCreate", _
		"ObjCreateInterface", _
		"ObjEvent", _
		"ObjEvent", _
		"ObjGet", _
		"ObjName", _
		"OnAutoItExitRegister", _
		"OnAutoItExitUnRegister", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Opt", _
		"Ping", _
		"PixelChecksum", _
		"PixelGetColor", _
		"PixelSearch", _
		"ProcessClose", _
		"ProcessExists", _
		"ProcessGetStats", _
		"ProcessList", _
		"ProcessSetPriority", _
		"ProcessWait", _
		"ProcessWaitClose", _
		"ProgressOff", _
		"ProgressOn", _
		"ProgressSet", _
		"Ptr", _
		"Random", _
		"RegDelete", _
		"RegEnumKey", _
		"RegEnumVal", _
		"RegRead", _
		"RegWrite", _
		"Round", _
		"Run", _
		"RunAs", _
		"RunAsWait", _
		"RunWait", _
		"Send", _
		"SendKeepActive", _
		"SetError", _
		"SetExtended", _
		"ShellExecute", _
		"ShellExecuteWait", _
		"Shutdown", _
		"Sin", _
		"Sleep", _
		"SoundPlay", _
		"SoundSetWaveVolume", _
		"SplashImageOn", _
		"SplashOff", _
		"SplashTextOn", _
		"Sqrt", _
		"SRandom", _
		"StatusbarGetText", _
		"StderrRead", _
		"StdinWrite", _
		"StdioClose", _
		"StdoutRead", _
		"String", _
		"StringAddCR", _
		"StringCompare", _
		"StringFormat", _
		"StringFromASCIIArray", _
		"StringInStr", _
		"StringIsAlNum", _
		"StringIsAlpha", _
		"StringIsASCII", _
		"StringIsDigit", _
		"StringIsFloat", _
		"StringIsInt", _
		"StringIsLower", _
		"StringIsSpace", _
		"StringIsUpper", _
		"StringIsXDigit", _
		"StringLeft", _
		"StringLen", _
		"StringLower", _
		"StringMid", _
		"StringRegExp", _
		"StringRegExpReplace", _
		"StringReplace", _
		"StringReverse", _
		"StringRight", _
		"StringSplit", _
		"StringStripCR", _
		"StringStripWS", _
		"StringToASCIIArray", _
		"StringToBinary", _
		"StringTrimLeft", _
		"StringTrimRight", _
		"StringUpper", _
		"Tan", _
		"TCPAccept", _
		"TCPCloseSocket", _
		"TCPConnect", _
		"TCPListen", _
		"TCPNameToIP", _
		"TCPRecv", _
		"TCPSend", _
		"TCPShutdown", _
		"TCPStartup", _
		"TimerDiff", _
		"TimerInit", _
		"ToolTip", _
		"TrayCreateItem", _
		"TrayCreateMenu", _
		"TrayGetMsg", _
		"TrayItemDelete", _
		"TrayItemGetHandle", _
		"TrayItemGetState", _
		"TrayItemGetText", _
		"TrayItemSetOnEvent", _
		"TrayItemSetState", _
		"TrayItemSetText", _
		"TraySetClick", _
		"TraySetIcon", _
		"TraySetOnEvent", _
		"TraySetPauseIcon", _
		"TraySetState", _
		"TraySetToolTip", _
		"TrayTip", _
		"UBound", _
		"UDPBind", _
		"UDPCloseSocket", _
		"UDPOpen", _
		"UDPRecv", _
		"UDPSend", _
		"UDPShutdown", _
		"UDPStartup", _
		"VarGetType", _
		"WinActivate", _
		"WinActive", _
		"WinClose", _
		"WinExists", _
		"WinFlash", _
		"WinGetCaretPos", _
		"WinGetClassList", _
		"WinGetClientSize", _
		"WinGetHandle", _
		"WinGetPos", _
		"WinGetProcess", _
		"WinGetState", _
		"WinGetText", _
		"WinGetTitle", _
		"WinKill", _
		"WinList", _
		"WinMenuSelectItem", _
		"WinMinimizeAll", _
		"WinMinimizeAllUndo", _
		"WinMove", _
		"WinSetOnTop", _
		"WinSetState", _
		"WinSetTitle", _
		"WinSetTrans", _
		"WinWait", _
		"WinWaitActive", _
		"WinWaitClose", _
		"WinWaitNotActive"]
