Global $__AL_MACROS[102] = [ _
		"@AppDataCommonDir", _
		"@AppDataDir", _
		"@AutoItExe", _
		"@AutoItPID", _
		"@AutoItVersion", _
		"@AutoItX64", _
		"@COM_EventObj", _
		"@CommonFilesDir", _
		"@Compiled", _
		"@ComputerName", _
		"@ComSpec", _
		"@CPUArch", _
		"@CR", _
		"@CRLF", _
		"@DesktopCommonDir", _
		"@DesktopDepth", _
		"@DesktopDir", _
		"@DesktopHeight", _
		"@DesktopRefresh", _
		"@DesktopWidth", _
		"@DocumentsCommonDir", _
		"@error", _
		"@exitCode", _
		"@exitMethod", _
		"@extended", _
		"@FavoritesCommonDir", _
		"@FavoritesDir", _
		"@GUI_CtrlHandle", _
		"@GUI_CtrlId", _
		"@GUI_DragFile", _
		"@GUI_DragId", _
		"@GUI_DropId", _
		"@GUI_WinHandle", _
		"@HomeDrive", _
		"@HomePath", _
		"@HomeShare", _
		"@HotKeyPressed", _
		"@HOUR", _
		"@IPAddress1", _
		"@IPAddress2", _
		"@IPAddress3", _
		"@IPAddress4", _
		"@KBLayout", _
		"@LF", _
		"@LocalAppDataDir", _
		"@LogonDNSDomain", _
		"@LogonDomain", _
		"@LogonServer", _
		"@MDAY", _
		"@MIN", _
		"@MON", _
		"@MSEC", _
		"@MUILang", _
		"@MyDocumentsDir", _
		"@NumParams", _
		"@OSArch", _
		"@OSBuild", _
		"@OSLang", _
		"@OSServicePack", _
		"@OSType", _
		"@OSVersion", _
		"@ProgramFilesDir", _
		"@ProgramsCommonDir", _
		"@ProgramsDir", _
		"@ScriptDir", _
		"@ScriptFullPath", _
		"@ScriptLineNumber", _
		"@ScriptName", _
		"@SEC", _
		"@StartMenuCommonDir", _
		"@StartMenuDir", _
		"@StartupCommonDir", _
		"@StartupDir", _
		"@SW_DISABLE", _
		"@SW_ENABLE", _
		"@SW_HIDE", _
		"@SW_LOCK", _
		"@SW_MAXIMIZE", _
		"@SW_MINIMIZE", _
		"@SW_RESTORE", _
		"@SW_SHOW", _
		"@SW_SHOWDEFAULT", _
		"@SW_SHOWMAXIMIZED", _
		"@SW_SHOWMINIMIZED", _
		"@SW_SHOWMINNOACTIVE", _
		"@SW_SHOWNA", _
		"@SW_SHOWNOACTIVATE", _
		"@SW_SHOWNORMAL", _
		"@SW_UNLOCK", _
		"@SystemDir", _
		"@TAB", _
		"@TempDir", _
		"@TRAY_ID", _
		"@TrayIconFlashing", _
		"@TrayIconVisible", _
		"@UserName", _
		"@UserProfileDir", _
		"@WDAY", _
		"@WindowsDir", _
		"@WorkingDir", _
		"@YDAY", _
		"@YEAR"]
